default: &default
  adapter: postgresql
  host: 127.0.0.1
  pool: 5
  timeout: 5000
  username: 
  password: 

development:
  <<: *default
  database: kudoserver_development

test:
  <<: *default
  database: kudoserver_test

production:
  <<: *default
  database: kudoserver_production